backend:
  name: git-gateway
  branch: main # ⭐️ 학생의 GitHub 창고 브랜치가 'master'라면 'master'로 수정하세요.

media_folder: "assets/images" # 이미지 업로드 시 저장될 폴더
public_folder: "/assets/images" # 이미지 업로드 시 사용될 경로

collections:
  - name: "cards"
    label: "유튜브 카테고리"
    files:
      - label: "메인 페이지 카드 목록"
        name: "mainList"
        file: "_data/cards.yml"
        fields:
          - label: "카드 목록"
            name: "mainList"
            widget: "list"
            fields:
              - { label: "제목", name: "title", widget: "string" }
              - { label: "아이콘 (이모티콘)", name: "icon", widget: "string" }
              - { label: "링크 (예: /게임유튜브.html)", name: "url", widget: "string" }
              - { label: "설명", name: "description", widget: "string" }
